# Generated by Django 5.2.17 on 2026-09-06 20:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, help_text='Operator brief — what success looks like.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('finished_with_errors', 'Finished with errors'), ('cancelled', 'Cancelled')], default='active', max_length=32)),
                ('focus_tags', models.JSONField(blank=True, default=list, help_text='Optional focus tags (domains/techniques); preferences only.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('phase', models.CharField(choices=[('recon', 'Reconnaissance'), ('initial-access', 'Initial access'), ('post-exploit', 'Post-exploitation'), ('reporting', 'Reporting')], default='recon', max_length=32)),
                ('mitre_techniques', models.JSONField(blank=True, default=list)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('blocked_reason', models.TextField(blank=True)),
                ('skill_suggestion', models.CharField(blank=True, help_text='Catalog skill id from SkillRegistry (e.g. network-scanner).', max_length=128)),
                ('profile_suggestion', models.CharField(blank=True, help_text='Optional agent role (e.g. OSINT-lead).', max_length=128)),
                ('commands', models.JSONField(blank=True, default=list, help_text='Dry-run command strings from the planner (not executed here).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependents', to='projects.objective')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'seq', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('lifecycle', models.CharField(choices=[('short', 'Short'), ('long', 'Long'), ('continuous', 'Continuous')], default='short', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('idle', 'Idle'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('skill_names', models.JSONField(blank=True, default=list, help_text='Catalog skill ids (SkillRegistry / SkillRouter).')),
                ('profile', models.CharField(blank=True, max_length=128)),
                ('plan_text', models.TextField(blank=True)),
                ('plan_path', models.CharField(blank=True, max_length=1024)),
                ('workspace_id', models.CharField(blank=True, max_length=64)),
                ('result', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.job')),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='projects.objective')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RulesOfEngagement',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='roe', serialize=False, to='projects.project')),
                ('in_scope', models.JSONField(blank=True, default=list, help_text='In-scope targets, e.g. ["8.8.8.8", "https://app.acme.com"]')),
                ('exclusions', models.JSONField(blank=True, default=list, help_text='Explicitly out-of-scope hosts/CIDRs/URLs.')),
                ('testing_window_notes', models.TextField(blank=True)),
                ('authorization_note', models.TextField(blank=True)),
                ('abort_triggers', models.TextField(blank=True)),
                ('opsec_notes', models.TextField(blank=True)),
                ('contacts', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rules of engagement',
                'verbose_name_plural': 'Rules of engagement',
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('osint', 'OSINT'), ('vulnerability', 'Vulnerability'), ('observation', 'Observation')], default='observation', max_length=32)),
                ('asset_type', models.CharField(blank=True, choices=[('domain', 'Domain'), ('ip', 'IP'), ('email', 'Email'), ('entity', 'Entity'), ('tenant', 'Tenant'), ('url', 'URL'), ('service', 'Service'), ('other', 'Other')], default='other', max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('false_positive', 'False positive'), ('fixed', 'Fixed'), ('accepted', 'Accepted risk')], default='open', max_length=20)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('service', models.CharField(blank=True, max_length=128)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=16)),
                ('cve_id', models.CharField(blank=True, max_length=64)),
                ('cwe_id', models.CharField(blank=True, max_length=32)),
                ('mitre_techniques', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('evidence_path', models.CharField(blank=True, max_length=1024)),
                ('remediation', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='projects.job')),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='projects.objective')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'seq', '-severity', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['project', 'status'], name='projects_ob_project_e44232_idx'),
        ),
        migrations.AddIndex(
            model_name='objective',
            index=models.Index(fields=['project', 'phase'], name='projects_ob_project_5b8fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['project', 'severity'], name='projects_fi_project_9aea36_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['project', 'status'], name='projects_fi_project_4b694d_idx'),
        ),
    ]
