# Generated by Django 5.2.17 on 2026-09-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_control_plane'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='operator_note',
            field=models.TextField(blank=True, help_text='Latest operator redirect / steer text (Phase 6).'),
        ),
    ]
