# Generated by Django 5.2.17 on 2026-09-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_streammessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='streammessage',
            new_name='projects_st_job_id_6d9f53_idx',
            old_name='projects_st_job_id_7a1c0f_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='lifecycle',
            field=models.CharField(choices=[('short', 'Short'), ('long', 'Long')], default='short', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='focus_tags',
            field=models.JSONField(blank=True, default=list, help_text='Soft SkillRouter preferred_tags (domains/techniques).'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished'), ('finished_with_errors', 'Finished with errors'), ('cancelled', 'Cancelled')], default='active', max_length=32),
        ),
    ]
