# Generated by Django 5.2.17 on 2026-09-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_job_operator_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesofengagement',
            name='candidates',
            field=models.JSONField(blank=True, default=list, help_text='Discovered assets awaiting promote-to-scope.'),
        ),
        migrations.AddField(
            model_name='rulesofengagement',
            name='seed',
            field=models.JSONField(blank=True, default=list, help_text='Engagement seeds / intent clues (not yet authorized attack targets).'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('domain', 'Domain'), ('ip', 'IP'), ('email', 'Email'), ('entity', 'Entity'), ('tenant', 'Tenant'), ('url', 'URL'), ('service', 'Service'), ('person', 'Person'), ('phone', 'Phone'), ('path', 'Path'), ('hash', 'Hash'), ('blob', 'Blob'), ('identity', 'Identity'), ('package', 'Package'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='rulesofengagement',
            name='exclusions',
            field=models.JSONField(blank=True, default=list, help_text='Explicitly out-of-scope targets (same shape as in_scope).'),
        ),
        migrations.AlterField(
            model_name='rulesofengagement',
            name='in_scope',
            field=models.JSONField(blank=True, default=list, help_text='Authorized targets as {"type","value"} objects (person, phone, domain, url, ip, path, hash, blob, …). Plain strings are coerced on read.'),
        ),
    ]
