# Generated by Django 5.2.17 on 2026-09-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_roe_typed_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='asset_type',
            field=models.CharField(blank=True, default='', help_text='Free-form asset/target type slug (skill/LLM); not a closed enum.', max_length=32),
        ),
        migrations.AlterField(
            model_name='finding',
            name='kind',
            field=models.CharField(default='observation', help_text='Free-form finding kind slug (skill/LLM); not a closed enum.', max_length=32),
        ),
    ]
