# Generated by Django 5.2.17 on 2026-10-01 21:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_sandbox_runtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('msg_type', models.CharField(choices=[('request', 'Request'), ('inform', 'Inform'), ('handoff', 'Handoff'), ('challenge', 'Challenge')], default='inform', max_length=16)),
                ('body', models.TextField()),
                ('artifact_refs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='jobdirective',
            new_name='projects_jo_job_id_f17e29_idx',
            old_name='projects_jo_job_id_c0f1a2_idx',
        ),
        migrations.RenameIndex(
            model_name='operatorprompt',
            new_name='projects_op_project_e2036d_idx',
            old_name='projects_op_project_7c1a2b_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='resume_from_checkpoint',
            field=models.BooleanField(default=False, help_text='Next agent run should continue LangGraph thread_id=job_id.'),
        ),
        migrations.AlterField(
            model_name='rulesofengagement',
            name='in_scope',
            field=models.JSONField(blank=True, default=list, help_text='Authorized targets as {"type","value"} (type is a soft hint). Plain strings are coerced on read.'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='from_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='projects.job'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_messages', to='projects.objective'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_messages', to='projects.project'),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='to_job',
            field=models.ForeignKey(blank=True, help_text='Null = broadcast to other jobs on the same objective.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='projects.job'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['to_job', 'consumed_at'], name='projects_ag_to_job__c72c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['objective', 'created_at'], name='projects_ag_objecti_af2576_idx'),
        ),
    ]
