# Generated by Django 5.2.17 on 2026-10-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_roles_replace_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='asset_type',
            field=models.CharField(blank=True, default='', help_text='Free-form asset/target type slug (role/LLM); not a closed enum.', max_length=32),
        ),
        migrations.AlterField(
            model_name='finding',
            name='kind',
            field=models.CharField(default='observation', help_text='Free-form finding kind slug (role/LLM); not a closed enum.', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='resume_from_checkpoint',
            field=models.BooleanField(default=False, help_text='Next agent run should resume the CrewAI role/crew with steer context.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='role_ids',
            field=models.JSONField(blank=True, default=list, help_text='CrewAI role ids from roles/ (RoleRegistry).'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='role_id',
            field=models.CharField(blank=True, help_text='CrewAI role id from roles/ (e.g. osint-expert).', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='focus_tags',
            field=models.JSONField(blank=True, default=list, help_text='Soft RoleRouter preferred tags (domains/techniques).'),
        ),
    ]
