# Generated by Django 5.2.6 on 2026-10-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_alter_finding_asset_type_alter_finding_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobdirective",
            name="kind",
            field=models.CharField(
                choices=[
                    ("steer", "Steer"),
                    ("followup", "Follow-up"),
                    ("replan", "Replan"),
                ],
                default="steer",
                max_length=16,
            ),
        ),
    ]
