"""Optional LiteLLM OpenAI-compatible proxy lifecycle (Settings toggle).

Peon agent traffic stays in-process. This gateway is for external clients
(OpenCode in Learn lab). Intent lives in ``PeonSettings``; process side starts
or stops the ``peon-litellm`` container on the Compose network.
"""

from __future__ import annotations

import json
import logging
from dataclasses import replace
from pathlib import Path
from typing import Any

from django.conf import settings

from agent_runtime.docker.cli import DockerCli
from orchestrator.config import configure, get_config
from orchestrator.utils.service import SharedServiceBase

logger = logging.getLogger(__name__)

_DEFAULT_CONFIG = """\
# Generated by Peon when LLM proxy is enabled from Settings.
model_list:
  - model_name: default
    litellm_params:
      model: os.environ/LITELLM_MODEL
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: openrouter/openai/gpt-4o-mini
    litellm_params:
      model: os.environ/LITELLM_MODEL
      api_key: os.environ/OPENROUTER_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
"""


class LlmProxy(SharedServiceBase):
    """Start/stop the LiteLLM /v1 gateway used by OpenCode."""

    def container_name(self) -> str:
        return str(
            getattr(settings, "LLM_PROXY_CONTAINER", None) or "peon-litellm"
        ).strip()

    def image(self) -> str:
        return str(
            getattr(settings, "LLM_PROXY_IMAGE", None)
            or "ghcr.io/berriai/litellm:main-stable"
        ).strip()

    def master_key(self) -> str:
        return str(
            getattr(settings, "LITELLM_MASTER_KEY", None) or "sk-peon-litellm"
        ).strip()

    def proxy_url(self) -> str:
        return str(
            getattr(settings, "LLM_PROXY_URL", None) or "http://litellm:4000/v1"
        ).strip() or "http://litellm:4000/v1"

    def host_port(self) -> int:
        raw = getattr(settings, "LLM_PROXY_PORT", 4000)
        try:
            return max(1, int(raw))
        except (TypeError, ValueError):
            return 4000

    def config_path(self) -> Path:
        root = Path(getattr(settings, "PEON_DATA_DIR", None) or (Path.cwd() / "data"))
        path = root.resolve() / "litellm" / "config.yaml"
        path.parent.mkdir(parents=True, exist_ok=True)
        return path

    @staticmethod
    def intent_enabled() -> bool:
        """Operator intent from Peon Settings (falls back to .env default)."""
        try:
            # circular: runtime_settings ↔ llm_proxy
            from peon.projects.runtime_settings import PeonSettings

            return PeonSettings.get_bool("LLM_PROXY_ENABLED", False)
        except Exception:
            return bool(getattr(settings, "LLM_PROXY_ENABLED", False))

    def sync_orchestrator(self, *, enabled: bool | None = None) -> None:
        on = self.intent_enabled() if enabled is None else bool(enabled)
        try:
            cfg = get_config()
            configure(
                replace(
                    cfg,
                    llm_proxy_enabled=on,
                    llm_proxy_url=self.proxy_url(),
                )
            )
        except Exception as exc:
            logger.warning("failed to sync llm proxy flag to orchestrator: %s", exc)

    def apply(self, enabled: bool) -> dict[str, Any]:
        """Honor Settings toggle: start or stop the gateway container."""
        self.sync_orchestrator(enabled=bool(enabled))
        if enabled:
            return self.ensure()
        return self.stop()

    def status(self) -> dict[str, Any]:
        cli = DockerCli.shared()
        name = self.container_name()
        ok, err = cli.daemon_ok()
        if not ok:
            return {
                "name": name,
                "exists": False,
                "running": False,
                "docker": False,
                "intent": self.intent_enabled(),
                "url": self.proxy_url(),
                "error": (err or "")[:300],
            }
        exists, running = cli.inspect_running(name)
        # Compose profile may have created peon-litellm-1 instead.
        if not exists:
            for alt in cli.ps_ids("name=peon-litellm"):
                exists, running = cli.inspect_running(alt)
                if exists:
                    name = alt
                    break
        return {
            "name": name,
            "exists": exists,
            "running": running,
            "docker": True,
            "intent": self.intent_enabled(),
            "url": self.proxy_url(),
            "error": "",
        }

    def snapshot(self) -> dict[str, Any]:
        """Operator-facing view: intent + live container status + URL."""
        st = self.status()
        intent = bool(st.get("intent"))
        return {
            "enabled": intent,
            "running": bool(st.get("running")),
            "url": self.proxy_url() if intent else None,
            "status": st,
        }

    def ensure(self) -> dict[str, Any]:
        cli = DockerCli.shared()
        cli.require_daemon()
        name = self.container_name()
        exists, running = cli.inspect_running(name)
        if exists and running:
            return {"ok": True, "action": "reused", "proxy": self.status()}
        if exists and not running:
            start = cli.start(name)
            if not start.ok:
                return {
                    "ok": False,
                    "action": "start_failed",
                    "error": (start.stderr or start.stdout or "").strip()[:400],
                    "proxy": self.status(),
                }
            return {"ok": True, "action": "started", "proxy": self.status()}

        config = self.config_path()
        if not config.is_file():
            config.write_text(_DEFAULT_CONFIG, encoding="utf-8")
        host_config = cli.host_bind_path(config)
        network = self._compose_network(cli)
        port = self.host_port()
        env = {
            "LITELLM_MODEL": str(
                getattr(settings, "LITELLM_MODEL", None)
                or "openrouter/openai/gpt-4o-mini"
            ),
            "OPENROUTER_API_KEY": str(
                getattr(settings, "OPENROUTER_API_KEY", None) or ""
            ),
            "OPENAI_API_KEY": str(getattr(settings, "OPENAI_API_KEY", None) or ""),
            "LITELLM_API_KEY": str(getattr(settings, "LITELLM_API_KEY", None) or ""),
            "LITELLM_MASTER_KEY": self.master_key(),
        }
        extra = [
            "--network-alias",
            "litellm",
            "-p",
            f"{port}:4000",
            "-v",
            f"{host_config}:/app/config.yaml:ro",
            "--label",
            "peon.llm_proxy=1",
            "--restart",
            "unless-stopped",
        ]
        create = cli.run_detached(
            name=name,
            image=self.image(),
            workdir="/app",
            network=network,
            env=env,
            extra_args=extra,
            command=[
                "--config",
                "/app/config.yaml",
                "--host",
                "0.0.0.0",
                "--port",
                "4000",
            ],
            timeout=180,
        )
        if not create.ok:
            err = (create.stderr or create.stdout or "").strip()
            # Race / name taken by compose service.
            exists2, running2 = cli.inspect_running(name)
            if exists2:
                if not running2:
                    cli.start(name)
                return {"ok": True, "action": "reused", "proxy": self.status()}
            return {
                "ok": False,
                "action": "create_failed",
                "error": err[:500],
                "proxy": self.status(),
            }
        return {"ok": True, "action": "created", "proxy": self.status()}

    def stop(self) -> dict[str, Any]:
        cli = DockerCli.shared()
        name = self.container_name()
        if not cli.available():
            return {
                "ok": False,
                "removed": False,
                "error": "docker unavailable",
                "proxy": self.status(),
            }
        removed = False
        for ref in [name, *cli.ps_ids("label=peon.llm_proxy=1")]:
            res = cli.rm_force(ref)
            if res.ok:
                removed = True
        return {"ok": True, "removed": removed, "proxy": self.status()}

    def _compose_network(self, cli: DockerCli) -> str:
        """Prefer the network this web/worker container is on."""
        preferred = str(
            getattr(settings, "LLM_PROXY_NETWORK", None) or "peon_default"
        ).strip()
        try:
            cid = cli.self_container_id()
            if cid:
                res = cli.inspect_format(
                    cid, "{{json .NetworkSettings.Networks}}", timeout=20
                )
                if res.ok and (res.stdout or "").strip():
                    nets = json.loads(res.stdout.strip())
                    if isinstance(nets, dict) and nets:
                        if preferred in nets:
                            return preferred
                        return next(iter(nets.keys()))
        except Exception as exc:
            logger.info("compose network probe failed: %s", exc)
        return preferred
